<a href="https://colab.research.google.com/github/sriramrangu/AI_DOC-copy/blob/master/LinearAlgibraPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix

In [1]:
import numpy as np

In [2]:
# Operations on Matrix
# - Addition
# - Subtraction
# - Scalar Multiplication ( Mulit )

In [3]:
# To create a matrix using numpy lib

In [4]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1 = np.array([[30,40,50],[10,15,30]])
a2 = np.array([[30,40,50],[10,15,30]])

In [6]:
print(a1, "\n\n")
print(a2)

[[30 40 50]
 [10 15 30]] 


[[30 40 50]
 [10 15 30]]


In [7]:
print(a1.shape)
print(a2.shape)

(2, 3)
(2, 3)


In [8]:
print(a1 + a2)

[[ 60  80 100]
 [ 20  30  60]]


In [9]:
# Subraction

In [10]:
print(a1 - a2)

[[0 0 0]
 [0 0 0]]


In [11]:
# Scalar Muliplication

In [12]:
print(a1 * 10)

[[300 400 500]
 [100 150 300]]


In [13]:
# Matrix Muliplication

In [14]:
print(a1 * a2)

[[ 900 1600 2500]
 [ 100  225  900]]


In [15]:
# print(np.dot(a1,a2))

In [16]:
a3 = np.array([[1],[2],[3]])

In [17]:
print(a3)

[[1]
 [2]
 [3]]


In [18]:
print(a3.shape)

(3, 1)


In [19]:
# Matrix Multiplication - using Dot Product

In [20]:
print(np.dot(a1,a3))

[[260]
 [130]]


In [21]:
# print(a1 * a3)

In [22]:
# Transpose of Matrix

In [23]:
print(a1,"\n")
print(a1.T,'\n')

print(a1.shape)
print(a1.T.shape)

[[30 40 50]
 [10 15 30]] 

[[30 10]
 [40 15]
 [50 30]] 

(2, 3)
(3, 2)


In [24]:
# Trace of Matrix -- Sum of diagnol elements of a Square matrix

In [25]:
m1 = np.array([[1,2],[3,4]])

In [26]:
print(m1)

[[1 2]
 [3 4]]


In [27]:
np.trace(m1)

np.int64(5)

In [28]:
# Rank - number of linearly independent rows or columns in a matrix is known as rank of a matrix

In [29]:
# Full Rank - if the elements are unique

In [30]:
m1 = np.array([[1,2],[3,4]])

In [31]:
print(m1)

[[1 2]
 [3 4]]


In [32]:
print(np.linalg.matrix_rank(m1))  # it will calculate the min of rows and cols

2


In [33]:
m2 = np.array([[1,2],[2,4]])

In [34]:
print(m2)

[[1 2]
 [2 4]]


In [35]:
print(np.linalg.matrix_rank(m2))

1


In [36]:
# Inverse of a Matrix

In [37]:
# to find inverse of a matrix
#  - matrix should be square matrix
#  - det of matrix should not equal to 0

In [38]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [39]:
print(np.linalg.det(a))

-2.0000000000000004


In [40]:
inverse_a = np.linalg.inv(a)

In [41]:
print(inverse_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [42]:
print(np.dot(a,inverse_a))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [45]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# Vector - a matrix which has one row or one column

In [47]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [48]:
v.shape

(3,)

In [53]:
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [ ]:
# Matrix Decompositon

In [ ]:
# LU Decompositon

In [55]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [56]:
from scipy.linalg import lu

In [57]:
P,L,U = lu(A)

In [59]:
print(P)

[[0. 1.]
 [1. 0.]]


In [60]:
print(L)

[[1.         0.        ]
 [0.33333333 1.        ]]


In [61]:
print(U)

[[3.         4.        ]
 [0.         0.66666667]]
